services:
  nginx:
    deploy:
      replicas: 0

  gateway:
    ports:
      - "${GATEWAY_PORT:-3000}:3000"
    volumes:
      - ./apps/gateway:/app
      - /app/node_modules

  workers:
    volumes:
      - ./apps/workers:/app
      - /app/node_modules

  ollama:
    ports:
      - "11434:11434"

  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  embedding:
    ports:
      - "8000:8000"
